[2022-01-29 12:37:12,941] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:12,988] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:12,989] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:12,989] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:12,989] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:13,055] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-02-02 06:00:00+00:00
[2022-01-29 12:37:13,068] {standard_task_runner.py:52} INFO - Started process 4891 to run task
[2022-01-29 12:37:13,090] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpw7rp3g6t', '--error-file', '/tmp/tmpttopa_11']
[2022-01-29 12:37:13,091] {standard_task_runner.py:77} INFO - Job 468: Subtask local_to_gcs_task
[2022-01-29 12:37:13,305] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-02-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:13,629] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-02T06:00:00+00:00
[2022-01-29 12:37:15,267] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:37:15,298] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210202T060000, start_date=20220129T123712, end_date=20220129T123715
[2022-01-29 12:37:15,392] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:15,479] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:20:49,138] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-29 13:20:49,151] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-02-02T06:00:00+00:00 [queued]>
[2022-01-29 13:20:49,151] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:20:49,151] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 13:20:49,151] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:20:49,164] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-02-02 06:00:00+00:00
[2022-01-29 13:20:49,170] {standard_task_runner.py:52} INFO - Started process 202 to run task
[2022-01-29 13:20:49,177] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-02-02T06:00:00+00:00', '--job-id', '536', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpibuy_t9p', '--error-file', '/tmp/tmprbb4nhzc']
[2022-01-29 13:20:49,178] {standard_task_runner.py:77} INFO - Job 536: Subtask local_to_gcs_task
[2022-01-29 13:20:49,250] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-02-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:20:49,299] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:20:49,325] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-02-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-02-02T06:00:00+00:00
[2022-01-29 13:20:50,258] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 13:20:50,271] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210202T060000, start_date=20220129T132049, end_date=20220129T132050
[2022-01-29 13:20:50,313] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:20:50,356] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
