[2022-01-29 12:37:17,820] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-09-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:17,858] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-09-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:17,859] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:17,859] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:17,859] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:17,900] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-09-02 06:00:00+00:00
[2022-01-29 12:37:17,921] {standard_task_runner.py:52} INFO - Started process 4923 to run task
[2022-01-29 12:37:17,951] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-09-02T06:00:00+00:00', '--job-id', '474', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpsrupejc1', '--error-file', '/tmp/tmpk_p2i1eb']
[2022-01-29 12:37:17,966] {standard_task_runner.py:77} INFO - Job 474: Subtask local_to_gcs_task
[2022-01-29 12:37:18,200] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-09-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:18,351] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-02T06:00:00+00:00
[2022-01-29 12:37:19,720] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:37:19,801] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210902T060000, start_date=20220129T123717, end_date=20220129T123719
[2022-01-29 12:37:19,878] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:19,936] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:14,707] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-09-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:14,797] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-09-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:14,797] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:14,797] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:14,797] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:14,880] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-09-02 06:00:00+00:00
[2022-01-29 13:23:14,917] {standard_task_runner.py:52} INFO - Started process 446 to run task
[2022-01-29 13:23:14,950] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-09-02T06:00:00+00:00', '--job-id', '559', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmprjvq7hhw', '--error-file', '/tmp/tmppxi0ssak']
[2022-01-29 13:23:14,967] {standard_task_runner.py:77} INFO - Job 559: Subtask local_to_gcs_task
[2022-01-29 13:23:15,376] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-09-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:15,710] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:15,843] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-02T06:00:00+00:00
[2022-01-29 13:23:16,401] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 13:23:16,602] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210902T060000, start_date=20220129T132314, end_date=20220129T132316
[2022-01-29 13:23:16,807] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:16,925] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
