[2022-01-29 12:37:56,699] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:56,716] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:56,717] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:56,717] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:56,717] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:56,737] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-11-02 06:00:00+00:00
[2022-01-29 12:37:56,746] {standard_task_runner.py:52} INFO - Started process 5016 to run task
[2022-01-29 12:37:56,759] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-11-02T06:00:00+00:00', '--job-id', '491', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpvxnji_7j', '--error-file', '/tmp/tmpi5n_y__6']
[2022-01-29 12:37:56,761] {standard_task_runner.py:77} INFO - Job 491: Subtask local_to_gcs_task
[2022-01-29 12:37:56,847] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:56,927] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-02T06:00:00+00:00
[2022-01-29 12:37:58,113] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:37:58,136] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20211102T060000, start_date=20220129T123756, end_date=20220129T123758
[2022-01-29 12:37:58,178] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:58,247] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:19,584] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:19,780] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:19,780] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:19,780] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:19,780] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:19,952] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-11-02 06:00:00+00:00
[2022-01-29 13:23:20,023] {standard_task_runner.py:52} INFO - Started process 477 to run task
[2022-01-29 13:23:20,043] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-11-02T06:00:00+00:00', '--job-id', '566', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmphhlbbv0k', '--error-file', '/tmp/tmp93e4vika']
[2022-01-29 13:23:20,072] {standard_task_runner.py:77} INFO - Job 566: Subtask local_to_gcs_task
[2022-01-29 13:23:20,504] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-11-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:20,932] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:21,148] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-11-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-02T06:00:00+00:00
[2022-01-29 13:23:21,875] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 13:23:22,041] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20211102T060000, start_date=20220129T132319, end_date=20220129T132322
[2022-01-29 13:23:22,246] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:22,371] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
