[2022-01-29 12:37:58,086] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-10-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:58,097] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-10-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:58,097] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:58,097] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:58,097] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:58,110] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-10-02 06:00:00+00:00
[2022-01-29 12:37:58,119] {standard_task_runner.py:52} INFO - Started process 5019 to run task
[2022-01-29 12:37:58,127] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-10-02T06:00:00+00:00', '--job-id', '493', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmphqzvia63', '--error-file', '/tmp/tmpn94ww900']
[2022-01-29 12:37:58,128] {standard_task_runner.py:77} INFO - Job 493: Subtask bigquery_external_table_task
[2022-01-29 12:37:58,263] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-10-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:58,371] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-02T06:00:00+00:00
[2022-01-29 12:37:58,373] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 12:37:58,840] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20211002T060000, start_date=20220129T123758, end_date=20220129T123758
[2022-01-29 12:37:58,906] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:59,091] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:25,725] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-10-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:25,827] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-10-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:25,827] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:25,828] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:25,828] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:25,903] {taskinstance.py:1259} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2021-10-02 06:00:00+00:00
[2022-01-29 13:23:25,921] {standard_task_runner.py:52} INFO - Started process 490 to run task
[2022-01-29 13:23:25,979] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'scheduled__2021-10-02T06:00:00+00:00', '--job-id', '568', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpuhpt3z23', '--error-file', '/tmp/tmp4x7e3tg9']
[2022-01-29 13:23:26,017] {standard_task_runner.py:77} INFO - Job 568: Subtask bigquery_external_table_task
[2022-01-29 13:23:26,666] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task scheduled__2021-10-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:27,042] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:27,514] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=bigquery_external_table_task
AIRFLOW_CTX_EXECUTION_DATE=2021-10-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-10-02T06:00:00+00:00
[2022-01-29 13:23:27,530] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-01-29 13:23:28,403] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, execution_date=20211002T060000, start_date=20220129T132325, end_date=20220129T132328
[2022-01-29 13:23:28,477] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:28,564] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
