[2022-01-29 12:37:56,709] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:56,722] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:56,722] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:56,722] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:56,723] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:56,737] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-12-02 06:00:00+00:00
[2022-01-29 12:37:56,744] {standard_task_runner.py:52} INFO - Started process 5015 to run task
[2022-01-29 12:37:56,752] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-12-02T06:00:00+00:00', '--job-id', '492', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp0uqbsru1', '--error-file', '/tmp/tmp4_l3dqvd']
[2022-01-29 12:37:56,754] {standard_task_runner.py:77} INFO - Job 492: Subtask local_to_gcs_task
[2022-01-29 12:37:56,858] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-12-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:56,946] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-02T06:00:00+00:00
[2022-01-29 12:37:58,186] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:37:58,212] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20211202T060000, start_date=20220129T123756, end_date=20220129T123758
[2022-01-29 12:37:58,298] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:58,352] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:16,616] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:16,750] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-12-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:16,750] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:16,750] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:16,750] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:16,883] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-12-02 06:00:00+00:00
[2022-01-29 13:23:16,990] {standard_task_runner.py:52} INFO - Started process 458 to run task
[2022-01-29 13:23:17,068] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-12-02T06:00:00+00:00', '--job-id', '565', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpr4499so2', '--error-file', '/tmp/tmpr8thwe3j']
[2022-01-29 13:23:17,070] {standard_task_runner.py:77} INFO - Job 565: Subtask local_to_gcs_task
[2022-01-29 13:23:17,517] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-12-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:17,896] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:18,116] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-12-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-02T06:00:00+00:00
[2022-01-29 13:23:19,333] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 13:23:19,486] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20211202T060000, start_date=20220129T132316, end_date=20220129T132319
[2022-01-29 13:23:19,869] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:20,156] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
