[2022-01-29 12:37:17,518] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:17,556] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:17,556] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:17,556] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:17,556] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:17,585] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-05-02 06:00:00+00:00
[2022-01-29 12:37:17,612] {standard_task_runner.py:52} INFO - Started process 4919 to run task
[2022-01-29 12:37:17,644] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp5389z_vz', '--error-file', '/tmp/tmpjwqv9o21']
[2022-01-29 12:37:17,651] {standard_task_runner.py:77} INFO - Job 473: Subtask local_to_gcs_task
[2022-01-29 12:37:17,837] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:18,056] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2022-01-29 12:37:19,180] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:37:19,210] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210502T060000, start_date=20220129T123717, end_date=20220129T123719
[2022-01-29 12:37:19,262] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:19,334] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:32,080] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:32,099] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:32,099] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:32,099] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:32,099] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:32,117] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-05-02 06:00:00+00:00
[2022-01-29 13:23:32,132] {standard_task_runner.py:52} INFO - Started process 503 to run task
[2022-01-29 13:23:32,149] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-05-02T06:00:00+00:00', '--job-id', '575', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpcx028951', '--error-file', '/tmp/tmptzkq0q57']
[2022-01-29 13:23:32,151] {standard_task_runner.py:77} INFO - Job 575: Subtask local_to_gcs_task
[2022-01-29 13:23:32,243] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-05-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:32,295] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:32,321] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-05-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-02T06:00:00+00:00
[2022-01-29 13:23:34,238] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 13:23:34,274] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210502T060000, start_date=20220129T132332, end_date=20220129T132334
[2022-01-29 13:23:34,336] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:34,400] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
