[2022-01-29 12:37:16,770] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-06-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:16,843] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-06-02T06:00:00+00:00 [queued]>
[2022-01-29 12:37:16,844] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:16,844] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-29 12:37:16,844] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 12:37:16,941] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-06-02 06:00:00+00:00
[2022-01-29 12:37:16,979] {standard_task_runner.py:52} INFO - Started process 4915 to run task
[2022-01-29 12:37:17,022] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-06-02T06:00:00+00:00', '--job-id', '470', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpiiuhhbz9', '--error-file', '/tmp/tmpo41g88ok']
[2022-01-29 12:37:17,024] {standard_task_runner.py:77} INFO - Job 470: Subtask local_to_gcs_task
[2022-01-29 12:37:17,405] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-06-02T06:00:00+00:00 [running]> on host 85e1117cfb12
[2022-01-29 12:37:17,597] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-02T06:00:00+00:00
[2022-01-29 12:37:18,840] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 12:37:18,865] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210602T060000, start_date=20220129T123716, end_date=20220129T123718
[2022-01-29 12:37:18,947] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 12:37:19,009] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-01-29 13:23:34,332] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-06-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:34,356] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-06-02T06:00:00+00:00 [queued]>
[2022-01-29 13:23:34,356] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:34,356] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-29 13:23:34,356] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-29 13:23:34,376] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-06-02 06:00:00+00:00
[2022-01-29 13:23:34,385] {standard_task_runner.py:52} INFO - Started process 508 to run task
[2022-01-29 13:23:34,397] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2021-06-02T06:00:00+00:00', '--job-id', '576', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpy0h1d_qm', '--error-file', '/tmp/tmpwy516031']
[2022-01-29 13:23:34,399] {standard_task_runner.py:77} INFO - Job 576: Subtask local_to_gcs_task
[2022-01-29 13:23:34,554] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2021-06-02T06:00:00+00:00 [running]> on host 9bf957887753
[2022-01-29 13:23:34,666] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-29 13:23:34,704] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-02T06:00:00+00:00
[2022-01-29 13:23:36,855] {python.py:175} INFO - Done. Returned value was: None
[2022-01-29 13:23:36,875] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, execution_date=20210602T060000, start_date=20220129T132334, end_date=20220129T132336
[2022-01-29 13:23:36,947] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-29 13:23:37,005] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
